[project]
name = "llm-conversion"
version = "0.1.0"
description = ""
authors = [
    {name = "johnny-emp",email = "johnny@empyrealsdk.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "emp-agents (>=0.2.0.post1,<0.3.0)",
    "python-dotenv (>=1.0.1,<2.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.12"

[tool.ruff]
ignore = ["E704"]
